// Mocks generated by Mockito 5.4.6 from annotations
// in crm_sales_performance_mobilis/test/unit/features/offres/data/offer_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:crm_sales_performance_mobilis/features/offres/data/offres_local_data_source.dart'
    as _i2;
import 'package:crm_sales_performance_mobilis/features/offres/models/offer_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OffresLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffresLocalDataSource extends _i1.Mock
    implements _i2.OffresLocalDataSource {
  MockOffresLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.OfferModel>> fetchOffers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOffers, []),
            returnValue: _i3.Future<List<_i4.OfferModel>>.value(
              <_i4.OfferModel>[],
            ),
          )
          as _i3.Future<List<_i4.OfferModel>>);

  @override
  _i3.Future<_i4.OfferModel?> fetchOfferById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOfferById, [id]),
            returnValue: _i3.Future<_i4.OfferModel?>.value(),
          )
          as _i3.Future<_i4.OfferModel?>);

  @override
  _i3.Future<void> addOffer(_i4.OfferModel? offer) =>
      (super.noSuchMethod(
            Invocation.method(#addOffer, [offer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateOffer(_i4.OfferModel? offer) =>
      (super.noSuchMethod(
            Invocation.method(#updateOffer, [offer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteOffer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOffer, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> seedInitialData() =>
      (super.noSuchMethod(
            Invocation.method(#seedInitialData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
