// Mocks generated by Mockito 5.4.6 from annotations
// in crm_sales_performance_mobilis/test/unit/features/authentication/presentation/cubit/auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:crm_sales_performance_mobilis/features/authentication/domain/login_repository.dart'
    as _i2;
import 'package:crm_sales_performance_mobilis/features/authentication/domain/otp_repository.dart'
    as _i3;
import 'package:crm_sales_performance_mobilis/features/authentication/domain/request_otp_usecase.dart'
    as _i5;
import 'package:crm_sales_performance_mobilis/features/authentication/domain/resend_otp_usecase.dart'
    as _i10;
import 'package:crm_sales_performance_mobilis/features/authentication/domain/verify_otp_usecase.dart'
    as _i8;
import 'package:crm_sales_performance_mobilis/features/authentication/models/auth_response.dart'
    as _i4;
import 'package:crm_sales_performance_mobilis/features/authentication/models/otp.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginRepository_0 extends _i1.SmartFake
    implements _i2.LoginRepository {
  _FakeLoginRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpRepository_1 extends _i1.SmartFake implements _i3.OtpRepository {
  _FakeOtpRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_2 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RequestOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestOtpUseCase extends _i1.Mock implements _i5.RequestOtpUseCase {
  MockRequestOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLoginRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LoginRepository);

  @override
  _i6.Future<String> call(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#call, [phoneNumber]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#call, [phoneNumber]),
              ),
            ),
          )
          as _i6.Future<String>);
}

/// A class which mocks [VerifyOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpUseCase extends _i1.Mock implements _i8.VerifyOtpUseCase {
  MockVerifyOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.OtpRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeOtpRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.OtpRepository);

  @override
  _i6.Future<_i4.AuthResponse> call(_i9.Otp? otp) =>
      (super.noSuchMethod(
            Invocation.method(#call, [otp]),
            returnValue: _i6.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_2(this, Invocation.method(#call, [otp])),
            ),
          )
          as _i6.Future<_i4.AuthResponse>);
}

/// A class which mocks [ResendOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendOtpUseCase extends _i1.Mock implements _i10.ResendOtpUseCase {
  MockResendOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.OtpRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeOtpRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.OtpRepository);

  @override
  _i6.Future<String> call(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#call, [phoneNumber]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#call, [phoneNumber]),
              ),
            ),
          )
          as _i6.Future<String>);
}
